# Generated by Django 5.0.1 on 2024-01-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0004_remove_message_sender_message_user_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                default="",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_app.room",
                verbose_name="Room",
            ),
        ),
    ]
