# Generated by Django 5.0.1 on 2024-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_message_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="online",
        ),
        migrations.AddField(
            model_name="room",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                max_length=300,
                unique=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
