# Generated by Django 5.0.1 on 2024-01-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0007_alter_room_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(
                blank=True, default="", max_length=300, unique=True, verbose_name="URL"
            ),
        ),
    ]
