# Generated by Django 5.0.1 on 2024-01-31 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0010_remove_post_user_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_app.profile",
                verbose_name="Post author",
            ),
        ),
    ]
