# Generated by Django 5.0.1 on 2024-02-02 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0013_remove_post_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                default="",
                max_length=300,
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chat participants",
            ),
        ),
    ]
