# Generated by Django 5.0.1 on 2024-02-02 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0014_room_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="participants",
        ),
        migrations.CreateModel(
            name="PostRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_liked",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        verbose_name="Liked or not",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_app.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "ordering": ("-post", "-author"),
            },
        ),
    ]
