# Generated by Django 5.0.1 on 2024-02-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0015_remove_room_participants_postrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="postrating",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postrating",
            name="post",
            field=models.ForeignKey(
                blank=True,
                default="",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_ratings",
                to="django_app.post",
                verbose_name="Post",
            ),
        ),
    ]
