# Generated by Django 5.0.1 on 2024-02-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0016_postrating_total_rating_alter_postrating_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postrating",
            name="total_rating",
        ),
        migrations.AlterField(
            model_name="postrating",
            name="post",
            field=models.ForeignKey(
                blank=True,
                default="",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_app.post",
                verbose_name="Post",
            ),
        ),
    ]
